# Generated by Django 4.2.3 on 2023-07-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('path', models.TextField()),
                ('video', models.TextField()),
                ('info', models.TextField(blank=True, null=True)),
                ('temp', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_id', models.TextField()),
                ('interval', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.TextField()),
                ('name', models.CharField(max_length=128)),
                ('url', models.TextField()),
                ('type', models.CharField(choices=[('p', 'Playlist'), ('c', 'Channel')], max_length=1)),
                ('quality', models.CharField(choices=[('a', 'Audio'), ('720', '720p'), ('1080', '1080p'), ('1440', '1440p'), ('2160', '4k'), ('max', 'Best')], max_length=4)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.outlet')),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.timer')),
            ],
        ),
    ]
