# Generated by Django 4.1.3 on 2023-07-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='interval',
        ),
        migrations.AddField(
            model_name='flow',
            name='timer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.timer'),
            preserve_default=False,
        ),
    ]
