# Generated by Django 4.2.3 on 2023-07-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_temp_outlet_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='timer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.timer'),
        ),
    ]
