# Generated by Django 4.1.3 on 2023-07-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_flow_interval_flow_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='flow_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
