name: publish
on: 
  release:
    types: [published]
jobs:
publish-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the Docker image
run: |
       docker build . --tag ghcr.io/SrAndromeda/Backloader-rework:latest
       docker run ghcr.io/SrAndromeda/Backloader-rework:latest
       docker push ghcr.io/SrAndromeda/Backloader-rework:latest